addCollaborators:
  newCollaboratorMessage: "This message will appear when someone opens a new issue, and is not already a collaborator."
  existingCollaboratorMessage: "This message appears when someone is already a collaborator and they open a new issue."
remindMerge:
  merged: "This message appears after Pull Request is merged."
  unmerged: "This message appears after Pull Request is closed without merging."
checkPath:
  name: "The name for the status check"
  path: "the_path_to_check"
  detailsURL: "https://link.to/more/details"
  success: "The message to display when the status check succeeds."
  failure: "The message to display when the status check fails."
checkExtension:
  name: "The name for the status check"
  extension: "the_extension_to_check"
  detailsURL: "https://link.to/more/details"
  success: "The message to display when the status check succeeds."
  failure: "The message to display when the status check fails."
reopenClosedIssues:
  message: "The message displayed when reopening new issues."
  whitelistedTeamID: <the GitHub Team ID to be whitelisted, should be a number>