addCollaborators:
  newCollaboratorMessage: "¡Hola! Soy el :robot: asistente de este repositorio (puedes llamarme El Robot).\n\n Me alegro de verte por aquí :wave:. Supongo que sabes lo que estás haciendo, así que voy a añadirte como usuario colaborador. Esto te dará permisos para hacer commits en este repositorio."
  existingCollaboratorMessage: ""
remindMerge:
  merged: ":tada: ¡Enhorabuena! Habéis integrado los cambios de alguien en el repositorio principal.\n\nAhora tenéis algunas tareas que hacer:\n\n- Ahora que ya habéis integrado los cambios, podéis eliminar el branch donde se han ido generando. Simplemente haced clic en el botón `Delete branch` aquí abajo.\n- El repositorio original ahora ha cambiado (con los cambios que acabáis de integrar). Acordaos de actualizar todas vuestras copias personales (tenéis instrucciones si os hacen falta).\n\nSi éste era el último PR que quedaba por integrar antes de la entrega, recordad también formalizar la entrega del apartado vía ALUD."
  unmerged: ":poop: Oops, parece que habéis cerrado este PR sin hacer merge. ¿Ha pasado algo?\n\nAunque el contenido no esté en condiciones de combinar todavía, podéis continuar haciendo modificaciones (commits) en este branch (aparecerán en la lista de actividad en esta misma página), y combinarlos cuando estén listos.\n\nNo dudéis en pedir ayura a @mberasategi (mi versión humana) si necesitáis ayuda con algo."
checkPath:
  name: "¿Están las actas de las reuniones?"
  path: "1-estrategia/actas"
  detailsURL: "https://link.to/more/details"
  success: "The message to display when the status check succeeds."
  failure: "The message to display when the status check fails."
reopenClosedIssues:
  message: "The message displayed when reopening new issues."
  whitelistedTeamID: <the GitHub Team ID to be whitelisted, should be a number>

