addCollaborators:
  newCollaboratorMessage: "¡Hola! Soy el :robot: asistente de este repositorio. \n\n Me alegro de verte por aquí :wave:. Supongo que sabes lo que estás haciendo, así que voy a añadirte como usuario colaborador. Esto te dará permisos para hacer commits en este repositorio."
  existingCollaboratorMessage: ""
remindMerge:
  merged: "This message appears after Pull Request is merged."
  unmerged: "This message appears after Pull Request is closed without merging."
checkPath:
  name: "The name for the status check"
  path: "the_path_to_check"
  detailsURL: "https://link.to/more/details"
  success: "The message to display when the status check succeeds."
  failure: "The message to display when the status check fails."
checkExtension:
  name: "The name for the status check"
  extension: "the_extension_to_check"
  detailsURL: "https://link.to/more/details"
  success: "The message to display when the status check succeeds."
  failure: "The message to display when the status check fails."
reopenClosedIssues:
  message: "The message displayed when reopening new issues."
  whitelistedTeamID: <the GitHub Team ID to be whitelisted, should be a number>
